apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab8.fullname" . }}-model
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lab8.name" . }}
      component: model
  template:
    metadata:
      labels:
        app: {{ include "lab8.name" . }}
        component: model
    spec:
      containers:
        - name: model
          image: {{ .Values.model.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_DB
              value: {{ .Values.redis.db | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab8.fullname" . }}-model
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "lab8.name" . }}
    component: model
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
