apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab8.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "lab8.name" . }}
      component: redis
  template:
    metadata:
      labels:
        app: {{ include "lab8.name" . }}
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab8.fullname" . }}-redis
spec:
  type: ClusterIP
  selector:
    app: {{ include "lab8.name" . }}
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
