image:
  repository: ghcr.io/osadcijm84/lab8
  tag: "latest"
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
redis:
  host: redis
  port: 6379
  db: 0
model:
  image: ghcr.io/osadcijm84/lab5-model:latest
source:
  image: ghcr.io/osadcijm84/lab6-source:latest
mart:
  image: ghcr.io/osadcijm84/lab7-mart:latest
replicaCount: 1
service:
  type: ClusterIP
  port: 8080
